### ISSUE TITLE
v0.0.13版本编译失败·

### ISSUE THREAD

**Issue by wcc526** [yetone/openai-translator#78]
```
> yarn run clean && node build.mjs

yarn run v1.22.18
$ rimraf dist
✨  Done in 0.46s.
(node:77429) ExperimentalWarning: The ESM module loader is experimental.
(node:77429) UnhandledPromiseRejectionWarning: TypeError: fs.rm is not a function
    at Object.remove (/Users/wcc526/Desktop/openai-translator-0.0.13/node_modules/fs-extra/lib/remove/index.js:7:6)
    at /Users/wcc526/Desktop/openai-translator-0.0.13/node_modules/universalify/index.js:10:14
    at new Promise (<anonymous>)
    at Object.remove (/Users/wcc526/Desktop/openai-translator-0.0.13/node_modules/universalify/index.js:7:14)
    at deleteOldDir (file:///Users/wcc526/Desktop/openai-translator-0.0.13/build.mjs:9:12)
    at build (file:///Users/wcc526/Desktop/openai-translator-0.0.13/build.mjs:52:9)
    at file:///Users/wcc526/Desktop/openai-translator-0.0.13/build.mjs:86:1
    at ModuleJob.run (internal/modules/esm/module_job.js:137:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
(node:77429) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:77429) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by maltoze** [comment]
node 版本发一下？ `v16.14.2` 下没问题
